from django.contrib import admin
from django.urls import path
from registeredUser import views

urlpatterns = [
    # path('',views.home,name = 'index'),
    path('login/', views.user_login,name="Userlogin"),
    path('logout/', views.Logout,name="Userlogout"),
    path('register/', views.register,name="register"),
    path('UserDashboard/', views.Userdashboard,name="UserDashboard"),
    path('UserBlank/', views.Userbuy,name="UserBuy"),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('stocks/', views.userstocks, name='userstocks'),
    # path('commodities/', views.usercommodities, name='usercommodities'),
    path('niftybees/', views.NIFTYbees,name="NIFTYbees"),
    path('goldbees/', views.GOLDbees,name="GOLDbees"),
    path('silverbees/', views.SILVERbees,name="SILVERbees"),
    path('itbees/', views.ITbees,name="ITbees"),
    path('sbietfit/', views.SBIetfit,name="SBIetfit"),
    path('tech/', views.Tech,name="Tech"),
      path('psubnk/', views.Psubnk,name="Psubnk"),
       path('nifit/', views.Nifitetf,name="Nifit"),
        path('movalue/', views.Movalue,name="Movalue"),
         path('mafang/', views.Mafang,name="Mafang"),
          path('kotak/', views.Kotak,name="Kotak"),
           path('iti/', views.Iti,name="Iti"),
            path('infrabees/', views.Infrabees,name="Infrabees"),
             path('icicib22/', views.Icicib22,name="Icicib22"),
              path('egold/', views.Egold,name="Egold"),
               path('dspq50/', views.Dspq50etf,name="Dspq50"),
                path('dspit/', views.Dspitetf,name="Dspit"),
                 path('cpse/', views.Cpseetf,name="Cpse"),
                  path('commoi/', views.Commoietf,name="Commoi"),
                   path('axistec/', views.Axistec,name="Axistec"),
                    path('abslnn/', views.Abslnn50et,name="Abslnn"),

    # path('account-verify/<token>',views.accout_verify, name='account-verify'),
    # path('userstocksdd/',views.userstocksdd, name="userstocksdropdown"),
    path('usercommoditiesdd/',views.usercommoditiesdd, name="usercommoditiesdropdown"),
    path('usertransactions/',views.Usertrans, name="usertrans"),
    path('userbuyhistory/', views.useralltrans, name='user_buy_history'),
    path('selletf/', views.usersell, name = 'sell_etf'),
    # path('buy_sell/', views.buy_sell, name = 'buy_sell'),
    
]
