# Generated by Django 4.2.6 on 2024-01-23 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
