# Generated by Django 4.2.6 on 2024-01-24 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registeredUser', '0004_alter_registereduser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
