# Generated by Django 4.2.6 on 2024-01-24 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeredUser', '0005_alter_registereduser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='user',
        ),
    ]
