# Generated by Django 4.0.2 on 2024-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredUser', '0006_remove_registereduser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='username',
            field=models.CharField(default='username', max_length=255, unique=True),
        ),
    ]
