# Generated by Django 5.0 on 2024-01-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registeredUser", "0007_registereduser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="registereduser",
            name="token",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
