# Generated by Django 4.2.6 on 2024-03-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredUser', '0009_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='trans_type',
            field=models.CharField(choices=[('Unsubscribed', 'Unsubscribed'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Unsubscribed', max_length=20),
        ),
    ]
