# Generated by Django 4.2.6 on 2024-03-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registeredUser', '0010_registereduser_trans_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registereduser',
            old_name='trans_type',
            new_name='sub_status',
        ),
    ]
