# Generated by Django 4.2.6 on 2024-04-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredUser', '0011_rename_trans_type_registereduser_sub_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='sub_status',
        ),
        migrations.AddField(
            model_name='wallet',
            name='period',
            field=models.CharField(choices=[('1 month', '1 month'), ('3 months', '3 months'), ('6 months', '6 months'), ('1 year', '1 year')], default='1 month', max_length=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='sub_status',
            field=models.CharField(choices=[('Unsubscribed', 'Unsubscribed'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Unsubscribed', max_length=20),
        ),
    ]
