# Generated by Django 4.2.6 on 2024-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredUser', '0012_remove_registereduser_sub_status_wallet_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='sub_status',
            field=models.CharField(choices=[('Unsubscribed', 'Unsubscribed'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], default='Unsubscribed', max_length=20),
        ),
    ]
