# Generated by Django 4.2.6 on 2024-04-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registeredUser', '0014_wallet_end_date_wallet_remaining_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
