# Generated by Django 4.0.2 on 2024-01-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NIFTYBEES_NS',
            fields=[
                ('date', models.DateField(default='-', primary_key=True, serialize=False)),
                ('Open', models.FloatField(default='-', null=True)),
                ('high', models.FloatField(default='-', null=True)),
                ('low', models.FloatField(default='-', null=True)),
                ('close', models.FloatField(default='-', null=True)),
                ('volume', models.BigIntegerField(default='-', null=True)),
                ('dividends', models.FloatField(default='-', null=True)),
                ('stock_splits', models.FloatField(default='-', null=True)),
            ],
        ),
    ]
