# Generated by Django 4.0.2 on 2024-01-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_admin', '0002_goldbees_ns_itbees_ns_sbitetfit_ns_silverbees_ns'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SBITETFIT_NS',
            new_name='SBIETFIT_NS',
        ),
    ]
