# Generated by Django 5.0 on 2024-02-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Custom_admin", "0003_rename_sbitetfit_ns_sbietfit_ns"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllETF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Etfnames", models.CharField(default="Name", max_length=225)),
                ("Open", models.FloatField(default="-", null=True)),
                ("high", models.FloatField(default="-", null=True)),
                ("low", models.FloatField(default="-", null=True)),
                ("close", models.FloatField(default="-", null=True)),
            ],
        ),
    ]
