# Generated by Django 5.0 on 2024-02-13 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Custom_admin", "0004_alletf"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AllETF",
        ),
    ]
