# Generated by Django 4.0.2 on 2024-02-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_admin', '0005_abslnn50et_ns_commoietf_ns_cpseetf_ns_dspitetf_ns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AXISTECETF_NS',
            fields=[
                ('date', models.DateField(default='-', primary_key=True, serialize=False)),
                ('Open', models.FloatField(default='-', null=True)),
                ('high', models.FloatField(default='-', null=True)),
                ('low', models.FloatField(default='-', null=True)),
                ('close', models.FloatField(default='-', null=True)),
                ('volume', models.BigIntegerField(default='-', null=True)),
                ('dividends', models.FloatField(default='-', null=True)),
                ('stock_splits', models.FloatField(default='-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DSPQ50ETF_NS',
            fields=[
                ('date', models.DateField(default='-', primary_key=True, serialize=False)),
                ('Open', models.FloatField(default='-', null=True)),
                ('high', models.FloatField(default='-', null=True)),
                ('low', models.FloatField(default='-', null=True)),
                ('close', models.FloatField(default='-', null=True)),
                ('volume', models.BigIntegerField(default='-', null=True)),
                ('dividends', models.FloatField(default='-', null=True)),
                ('stock_splits', models.FloatField(default='-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='INFRABEES_NS',
            fields=[
                ('date', models.DateField(default='-', primary_key=True, serialize=False)),
                ('Open', models.FloatField(default='-', null=True)),
                ('high', models.FloatField(default='-', null=True)),
                ('low', models.FloatField(default='-', null=True)),
                ('close', models.FloatField(default='-', null=True)),
                ('volume', models.BigIntegerField(default='-', null=True)),
                ('dividends', models.FloatField(default='-', null=True)),
                ('stock_splits', models.FloatField(default='-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KOTAKPSUBK_NS',
            fields=[
                ('date', models.DateField(default='-', primary_key=True, serialize=False)),
                ('Open', models.FloatField(default='-', null=True)),
                ('high', models.FloatField(default='-', null=True)),
                ('low', models.FloatField(default='-', null=True)),
                ('close', models.FloatField(default='-', null=True)),
                ('volume', models.BigIntegerField(default='-', null=True)),
                ('dividends', models.FloatField(default='-', null=True)),
                ('stock_splits', models.FloatField(default='-', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TECH_NS',
            fields=[
                ('date', models.DateField(default='-', primary_key=True, serialize=False)),
                ('Open', models.FloatField(default='-', null=True)),
                ('high', models.FloatField(default='-', null=True)),
                ('low', models.FloatField(default='-', null=True)),
                ('close', models.FloatField(default='-', null=True)),
                ('volume', models.BigIntegerField(default='-', null=True)),
                ('dividends', models.FloatField(default='-', null=True)),
                ('stock_splits', models.FloatField(default='-', null=True)),
            ],
        ),
    ]
