# Generated by Django 5.0 on 2024-02-13 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Custom_admin", "0006_alletf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alletf",
            name="Date",
        ),
    ]
