# Generated by Django 5.0 on 2024-02-18 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Custom_admin", "0006_axistecetf_ns_dspq50etf_ns_infrabees_ns_and_more"),
        ("Custom_admin", "0007_remove_alletf_date"),
    ]

    operations = []
