# Generated by Django 4.0.2 on 2024-02-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registeredUser', '0009_wallet'),
        ('Custom_admin', '0009_alletf_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuyetf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date and Time')),
                ('Quantity', models.IntegerField(max_length=20, null=True)),
                ('Cost', models.IntegerField(max_length=20, null=True)),
                ('Etf_purchased', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Custom_admin.alletf')),
                ('Username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registeredUser.registereduser')),
            ],
        ),
    ]
