# Generated by Django 4.0.2 on 2024-02-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Custom_admin', '0012_alletf_userbuyetf'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuyetf',
            name='Purchase_close_value',
            field=models.FloatField(null=True),
        ),
    ]
